version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pengin-pi-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - tobuweb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: pengin-pi-web
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app # Using relative path for better portability
      - static_volume:/app/staticfiles # Static files are still collected into a separate volume
      # - media_volume:/app/media # Uncomment if you have a media directory
    expose:
      - 8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${DOMAIN}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      # Add other environment variables from your settings.py here
      - SES_HOST=${SES_HOST}
      - SES_USERNAME_SMTP=${SES_USERNAME_SMTP}
      - SES_PASSWORD_SMTP=${SES_PASSWORD_SMTP}
      - SES_SENDER_NAME=${SES_SENDER_NAME}
      - SES_SENDER=${SES_SENDER}
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@ferretdb:27017/
      - MONGODB_DB_NAME=${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      - redis
      - ferretdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pengin-pi.rule=Host(`tobupengin.com`) || Host(`www.tobupengin.com`)"
      - "traefik.http.routers.pengin-pi.entrypoints=websecure"
      - "traefik.http.routers.pengin-pi.tls.certresolver=letsencrypt"
      - "traefik.http.services.pengin-pi.loadbalancer.server.port=8000"
      - "traefik.docker.network=root_proxy"
    networks:
      - tobuweb
      - root_proxy

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: pengin-pi-ferretdb
    restart: always
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    ports:
      - "27017:27017"
    depends_on:
      - postgres
    networks:
      - tobuweb

  redis:
    image: redis:6-alpine
    container_name: pengin-pi-redis
    restart: always
    networks:
      - tobuweb

volumes:
  postgres_data:
  static_volume:

networks:
  tobuweb:
  proxy:
    external: true
    name: root_proxy