"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-14nmqptb91000ao@b&c-a1*%=8b)!f-g2=^gsxcbo+d7!h&onj')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

#LOGIN REDIRECT
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

#ALLOWED HOSTS
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')

# Whether main.views.subscription.SubscribeView requires a logged-in
# account (True) or also accepts an anonymous email address confirmed via
# a signed link (False, the default) - see main/models/subscription.py's
# module docstring for the reasoning. A site-level policy choice, not a
# core capability restriction: core supports both paths either way.
SUBSCRIPTIONS_REQUIRE_ACCOUNT = config('SUBSCRIPTIONS_REQUIRE_ACCOUNT', default=False, cast=bool)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ratelimit',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django_redis',
    'markdownit',
    'macros',
    # Add your apps below here:
    'main',
    'blogs',
]

SITE_ID = 1

load_dotenv()

# --- Optional subsystem detection ---------------------------------------
# AWS/Google credentials are optional. Each integration below is only wired
# up if its required keys are present in the environment; otherwise it is
# disabled and the app falls back to a safe local/no-op default instead of
# crashing at import time or failing at request time.
AWS_SES_ENABLED = bool(
    config('SES_USERNAME_SMTP', default='')
    and config('SES_PASSWORD_SMTP', default='')
    and config('SES_SENDER', default='')
)
AWS_S3_ENABLED = bool(
    config('S3_KEY', default='')
    and config('S3_SECRET', default='')
    and config('S3_BUCKET', default='')
)
RECAPTCHA_ENABLED = bool(
    config('RECAPTCHA_SITE_KEY', default='')
    and config('RECAPTCHA_SECRET_KEY', default='')
)

# Email settings
if AWS_SES_ENABLED:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('SES_HOST', default='email-smtp.us-west-2.amazonaws.com')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('SES_USERNAME_SMTP')
    EMAIL_HOST_PASSWORD = config('SES_PASSWORD_SMTP')
    DEFAULT_FROM_EMAIL = f"{config('SES_SENDER_NAME', default='')} <{config('SES_SENDER')}>"
else:
    # No SES credentials configured - don't attempt to send mail over SMTP.
    # Emails are printed to the console instead of being delivered.
    print("[settings] SES credentials not found - email sending is disabled (console backend).")
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = f"{config('SES_SENDER_NAME', default='')} <{config('SES_SENDER', default='noreply@localhost')}>"

MIDDLEWARE = [
    'util.middleware.blocklist.HardenedBlocklistMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'util.middleware.analytics.PageViewLoggerMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'util.context_processors.recaptcha_context',
                'main.auth.context_processors.auth_context',
                'main.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Default to SQLite for local development
# Docker environment variables will override this for production
_db_engine = config('DB_ENGINE', default='django.db.backends.sqlite3')
_db_name = config('DB_NAME', default='')
_db_user = config('DB_USER', default='')
_db_password = config('DB_PASSWORD', default='')
_db_host = config('DB_HOST', default='')
_db_port = config('DB_PORT', default='')

# A non-sqlite engine needs NAME/USER/PASSWORD/HOST to actually connect. If
# any of those are missing (e.g. DB_ENGINE=postgresql copied over without the
# rest), fall back to a local SQLite file instead of failing at request time.
if _db_engine != 'django.db.backends.sqlite3' and not (_db_name and _db_user and _db_password and _db_host):
    print(f"[settings] DB_ENGINE={_db_engine} requested but DB_NAME/DB_USER/DB_PASSWORD/DB_HOST are incomplete - falling back to local SQLite database.")
    _db_engine = 'django.db.backends.sqlite3'

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': _db_name or (BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': _db_name,
            'USER': _db_user,
            'PASSWORD': _db_password,
            'HOST': _db_host,
            'PORT': _db_port or None,
        }
    }
MONGODB_URI = config('MONGODB_URI', default="mongodb://ferretdb:27017/")
MONGODB_DB_NAME = config('MONGODB_DB_NAME', default="dynamic_cms")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config('REDIS_URL', default="redis://127.0.0.1:6379"),
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# forces Django to use custom User model main.models.users.__init__.py User
AUTH_USER_MODEL = 'main.User'

DEFAULT_USER_ID = 1

# Reverse Proxy & HTTPS Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Enforce HTTPS-only session and CSRF cookies - configurable rather than
# hardcoded so a genuinely TLS-less deployment (e.g. an internal, LAN/VPN
# -only server with no public-facing cert) can turn this off; every
# public site keeps the secure-by-default True.
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)

# Security headers
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Required for Django 4.0+ CSRF protection behind HTTPS proxy
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',') if config('CSRF_TRUSTED_ORIGINS', default='') else []

# Session
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # After 30 minutes the cookie expires

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# The directory where collectstatic will collect static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Use for deployment

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File storage backend
FILE_STORAGE_BACKEND = config('FILE_STORAGE_BACKEND', default='local') # 's3' or 'local'
if FILE_STORAGE_BACKEND == 's3' and not AWS_S3_ENABLED:
    print("[settings] FILE_STORAGE_BACKEND=s3 but S3_KEY/S3_SECRET/S3_BUCKET are missing - falling back to local storage.")
    FILE_STORAGE_BACKEND = 'local'

# Media files (uploads)
# https://docs.djangoproject.com/en/5.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
