# Generated by Django 6.0.6 on 2026-08-12 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('email_alias', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page View Log',
                'verbose_name_plural': 'Page View Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
