# Generated by Django 6.0.5 on 2026-09-09 03:41

import django.db.models.deletion
import django.utils.timezone
import main.models.mixins
import util.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0013_event_eventhistory_eventparticipant_eventreservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('file', models.CharField(blank=True, help_text='Stored FileIO/S3 key', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, help_text='Display title for attached file', max_length=255, null=True)),
                ('is_event', models.BooleanField(default=False, help_text='Check if this blog post is announcing a calendar event.')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Associated event details.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='main.event')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date'],
            },
            bases=(main.models.mixins.SitemapEntry, main.models.mixins.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogHistory',
            fields=[
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='blogs.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Blog Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
    ]
