# Generated by Django 6.0.2 on 2026-02-13 18:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(default='Error Getting Title', max_length=100)),
                ('user', models.UUIDField(db_index=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('method', models.CharField(default='ERROR', max_length=10)),
                ('roles', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('method', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
    ]
