# Generated by Django 6.1.1 on 2026-09-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Public-facing SEO description (<meta name="description">). Falls back to a truncated excerpt of the content if left blank.', max_length=300),
        ),
    ]
