# Generated by Django 5.1.1 on 2024-09-13 20:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(default='Error Getting Title', max_length=100)),
                ('user', models.UUIDField(db_index=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('method', models.CharField(default='ERROR', max_length=10)),
                ('roles', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='method',
            field=models.CharField(default='ERROR', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
