[Definition]
# Matches lines in fail2ban.log where the 'recidive' jail executed a ban -
# i.e. an IP that's already been banned by one of our other jails,
# unbanned, and re-offended. That IP gets escalated to a permanent ban.
failregex = ^\s*(?:<MSG> )?NOTICE\s+\[recidive\]\s+Ban\s+<HOST>\s*$
ignoreregex =
