# Generated by Django 6.0.1 on 2026-02-01 22:24

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=102)),
                ('name', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('validation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('prt', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('prt_reset_date', models.DateTimeField(blank=True, null=True)),
                ('prt_consumption_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='%(app_label)s_%(class)s_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(app_label)s_%(class)s_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2026, 2, 1, 22, 24, 53, 818726, tzinfo=datetime.timezone.utc))),
                ('modify_date', models.DateTimeField(default=datetime.datetime(2026, 2, 1, 22, 24, 53, 818745, tzinfo=datetime.timezone.utc))),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AddressHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address_id', models.UUIDField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address Histories',
            },
        ),
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('meta_tags', models.CharField(max_length=300)),
                ('meta_description', models.CharField(max_length=300)),
                ('template_name', models.CharField(max_length=300)),
                ('render_template', models.TextField()),
                ('json', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2026, 2, 1, 22, 24, 54, 136832, tzinfo=datetime.timezone.utc))),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.slug', verbose_name='Parent Slug')),
            ],
            options={
                'verbose_name_plural': 'Slugs',
            },
        ),
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('meta_tags', models.CharField(max_length=300)),
                ('meta_description', models.CharField(max_length=150)),
                ('template_name', models.CharField(max_length=300)),
                ('render_template', models.TextField()),
                ('json', models.TextField()),
                ('date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_children', to='main.slughistory')),
            ],
            options={
                'verbose_name_plural': 'Slug Histories',
            },
        ),
    ]
