# Generated by Django 6.0.2 on 2026-05-12 00:00

import util.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slughistory',
            name='snapshot',
            field=models.JSONField(encoder=util.utils.UUIDEncoder),
        ),
    ]
