# Generated by Django 6.0.6 on 2026-07-24 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_slughistory_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='validation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
