# Generated by Django 6.0.1 on 2026-02-01 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_address_date_alter_address_modify_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slug',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='creator',
        ),
        migrations.AddField(
            model_name='slug',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slugs_created', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='slughistory',
            name='last_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slug_histories_as_last_author', to=settings.AUTH_USER_MODEL, verbose_name='Last Author'),
        ),
        migrations.AddField(
            model_name='slughistory',
            name='modify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slug_histories_as_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modifier'),
        ),
        migrations.AddField(
            model_name='slughistory',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='main.slug'),
        ),
        migrations.AlterField(
            model_name='slug',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slughistory',
            name='modify_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slughistory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_children', to='main.slug'),
        ),
    ]
