# Generated by Django 6.0.1 on 2026-02-01 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_slug_creator_remove_slughistory_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresshistory',
            name='address_id',
        ),
        migrations.AddField(
            model_name='addresshistory',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_address', to='main.address'),
        ),
    ]
