# Generated by Django 6.0.1 on 2026-02-04 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_addresshistory_address_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slughistory',
            options={'ordering': ('-changed_at',), 'verbose_name_plural': 'Slug Histories'},
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='json',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='render_template',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='template_name',
        ),
        migrations.AddField(
            model_name='slughistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slughistory',
            name='object',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slughistory',
            name='snapshot',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slug',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slugs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slug',
            name='json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slug',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.slug'),
        ),
        migrations.AlterField(
            model_name='slug',
            name='render_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slug',
            name='template_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='slughistory',
            name='last_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slughistory',
            name='modify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
