# Generated by Django 6.0.5 on 2026-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(default='*', max_length=50)),
                ('path', models.CharField(help_text='Path pattern e.g. /admin/ or /slug/edit/', max_length=255)),
                ('allow', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Robots Rules',
            },
        ),
        migrations.AddField(
            model_name='slug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
