# Generated by Django 6.0.5 on 2026-09-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0007_sequencecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='slug',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='slug',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slug',
            name='json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
