# Generated by Django 6.0.5 on 2026-09-08 06:13

import django.db.models.deletion
import util.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slughistory',
            options={'ordering': ['-changed_at'], 'verbose_name_plural': 'Slug Histories'},
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='last_author',
        ),
        migrations.RemoveField(
            model_name='slughistory',
            name='modify_user',
        ),
        migrations.AddField(
            model_name='slughistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder),
        ),
        migrations.AlterField(
            model_name='slughistory',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder),
        ),
    ]
