# Generated by Django 6.0.5 on 2026-09-08 21:34

import django.db.models.deletion
import main.models.mixins
import util.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_alter_slughistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Title, e.g. 'Manager'.", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_manager_role', models.BooleanField(default=False, help_text='Manager-tier title for this department - grants department-wide authority to anyone holding it. See main/auth/permissions.py.')),
                ('group', models.ForeignKey(help_text='The department (Group) this title belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_roles', to='auth.group')),
            ],
            options={
                'verbose_name': 'Team Role',
                'verbose_name_plural': 'Team Roles',
                'ordering': ['group', 'name'],
                'unique_together': {('group', 'name')},
            },
            bases=(main.models.mixins.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamRoleHistory',
            fields=[
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.teamrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team Role Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamUserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='main.teamrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team User Role Assignment',
                'verbose_name_plural': 'Team User Role Assignments',
                'unique_together': {('user', 'role')},
            },
            bases=(main.models.mixins.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamUserRoleHistory',
            fields=[
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.teamuserrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team User Role Assignment Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
    ]
