# Generated by Django 6.0.5 on 2026-09-09 01:12

import django.db.models.deletion
import main.models.mixins
import util.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teamrole_teamrolehistory_teamuserrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('webmaster', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site',
            },
            bases=(main.models.mixins.HistoryMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='addresshistory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addresshistory',
            name='modify_user',
        ),
        migrations.CreateModel(
            name='SiteHistory',
            fields=[
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressHistory',
        ),
    ]
