# Generated by Django 6.0.5 on 2026-09-09 03:28

import django.db.models.deletion
import django.utils.timezone
import main.models.mixins
import util.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0012_site_remove_addresshistory_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('internal', 'Internal (staff/team only)'), ('validated_public', 'Validated Public (any validated account)'), ('public', 'Public (anyone, incl. anonymous visitors)')], default='internal', help_text='Who can see this event. Public events appear on the public calendar page.', max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=300)),
                ('render_template', models.TextField(blank=True)),
                ('json', models.JSONField(blank=True, default=dict)),
                ('is_public_reservable_time', models.BooleanField(default=False, help_text='Any validated, active user may reserve a time slot on this event.')),
                ('is_internal_reservable_time', models.BooleanField(default=False, help_text="Staff, or members of this event's roles, may reserve a time slot.")),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recur_until', models.DateField(blank=True, help_text='Last date this weekly-recurring event still appears on the calendar.', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_events', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, help_text='Leave blank to make this event visible regardless of role.', related_name='events', to='auth.group')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
            bases=(main.models.mixins.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=util.utils.UUIDEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Histories',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participants_added', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.event')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_start'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'start_datetime'], name='event_visibility_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='event_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_datetime'], name='event_end_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='eventreservation',
            unique_together={('event', 'occurrence_date', 'slot_start')},
        ),
    ]
