# Generated by Django 6.0.5 on 2026-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event_eventhistory_eventparticipant_eventreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slug',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
