# Generated by Django 6.1.1 on 2026-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_slug_is_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='slug',
            name='requires_recaptcha',
            field=models.BooleanField(default=False, help_text="If this page's content embeds a form that posts back to it, require a valid reCAPTCHA token on that POST."),
        ),
    ]
