# Generated by Django 6.1.1 on 2026-09-14 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_subscription_subscriptionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slug',
            name='wiki_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slug',
            name='wiki_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to='main.slug'),
        ),
    ]
