# Generated by Django 6.1.1 on 2026-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_slug_wiki_body_slug_wiki_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrole',
            name='is_blog_author_role',
            field=models.BooleanField(default=False, help_text="Blogger title - grants CRUD authority over every blog post on the site (there's only one Blogs app, not one per department, so this flag isn't scoped to a specific department the way is_forum_moderator_role is). See main/auth/permissions.py."),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='is_forum_moderator_role',
            field=models.BooleanField(default=False, help_text="Forum-moderator title for this department - grants CRUD-on-posts and ban authority over this department's own forum thread (or, for the two site-wide departments, every forum thread on the site). Independent of is_manager_role - moderating a forum and managing a department's roster are separate authorities that don't have to be held by the same title. See main/auth/permissions.py."),
        ),
    ]
