# Generated by Django 6.0.2 on 2026-02-13 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=150)),
            ],
        ),
    ]
