# Generated by Django 5.1.1 on 2024-09-13 18:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_action', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForumCommentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_id', models.UUIDField(db_index=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.UUIDField(db_index=True)),
                ('user', models.UUIDField(db_index=True)),
                ('row_action', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_action', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.UUIDField(db_index=True)),
                ('user', models.UUIDField(db_index=True)),
                ('row_action', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_action', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.UUIDField(db_index=True)),
                ('roles', models.JSONField()),
                ('row_action', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
